apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cloud_service: kafka
    cloud_tier: web
    cloud_team: ops
    cluster: tirth-test
    strimzi_io_cluster: tirth-test
    strimzi_io_kind: Kafka
  name: kafka-exporter-tirth-test
spec:
  replicas: 1
  selector:
    matchLabels:
      cloud_service: kafka
      cloud_tier: web
      cloud_team: ops
      cluster: tirth-test
      strimzi_io_cluster: tirth-test
      strimzi_io_kind: Kafka
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        cloud_service: kafka
        cloud_tier: web
        cloud_team: ops
        cluster: tirth-test
        strimzi_io_cluster: tirth-test
        strimzi_io_kind: Kafka
    spec:
      nodeSelector:
        pool-name: misc
      imagePullSecrets:
        - name: inception-image-access
      containers:
        - command: ['/bin/kafka_exporter', '--kafka.server=tirth-test-kafka-bootstrap:9092']
          image: danielqsj/kafka-exporter:v1.4.2
          imagePullPolicy: IfNotPresent
          name: kafka-exporter
          ports:
            - containerPort: 9308
              name: kafka-mts
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 64Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
