apiVersion: v1
data:
  log4j.properties: |-
    log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
    log4j.appender.CONSOLE.layout=net.logstash.log4j.JSONEventLayoutV1
    kafka.root.logger.level=INFO
    log4j.rootLogger=${kafka.root.logger.level}, CONSOLE
    log4j.logger.kafka=INFO
    log4j.logger.org.apache.kafka=INFO
kind: ConfigMap
metadata:
  name: tirth-test-json-logging-kafka
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tirth-test-kafka-metrics-config
data:
  metrics-config: |
    lowercaseOutputName: false
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: tirth-test
  labels:
    cloud_service: kafka
    cloud_tier: web
    cloud_team: ops
spec:
  kafka:
    version: 3.1.0
    replicas: 1
    template:
      pod:
        tmpDirSizeLimit: 100Mi
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: tirth-test-kafka-metrics-config
          key: metrics-config
    resources:
      requests:
        memory: 2Gi
        cpu: "500m"
    jvmOptions:
      "-Xmx": "1g"
      "-Xms": "1g"
    logging:
      type: external
      valueFrom:
        configMapKeyRef:
          name: tirth-test-json-logging-kafka
          key: log4j.properties
    listeners:
     - name: plain
       port: 9092
       type: internal
       tls: false
    config:
      auto.create.topics.enable: "true"
      offsets.topic.replication.factor: 1
      num.partitions: 1
      default.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.retention.hours: 24
      log.retention.bytes: 51310542629
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 512Gi
        deleteClaim: false
  zookeeper:
    replicas: 1
    template:
      pod:
        tmpDirSizeLimit: 100Mi
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
    jvmOptions:
      "-Xmx": "256m"
      "-Xms": "256m"
  entityOperator:
    template:
      pod:
        tmpDirSizeLimit: 100Mi
    topicOperator: {}
    userOperator: {}
